import RestaurantNav from "@/app/restaurant/components/RestaurantNav";
import Menu from "@/app/restaurant/components/Menu";
import {PrismaClient} from "@prisma/client";

const prisma = new PrismaClient();

const fetchRestaurantMenu = async (slug: string) => {
    const restaurant = await prisma.restaurant.findUnique({
        where: {
            slug
        },
        select: {
            items: true
        }
    });

    if(!restaurant) {
        throw new Error();
    }

    return restaurant.items;
}

export const metadata = {
    title: 'Menu | Test Restaurant | OpenTable',
    description: 'Generated by create next app',
}
export default async function RestaurantMenu({params}: {params: {slug: string}}) {
    const menu = await fetchRestaurantMenu(params.slug)

    return (
        <>
            <div className="bg-white w-[100%] rounded p-3 shadow">
                <RestaurantNav slug={params.slug}/>
                <Menu menu={menu}/>
            </div>
        </>
    )
}