import Header from "@/app/reserve/components/Header";
import Form from "@/app/reserve/components/Form";

export const metadata = {
    title: 'Make a reservation | Test Restaurant | OpenTable',
    description: 'Generated by create next app',
}
export default function ReserveRestaurant() {
    return (
        <>
            <div className="border-t h-screen">
                <div className="py-9 w-3/5 m-auto">
                    <Header/>
                    <Form/>
                </div>
            </div>
        </>
    )
}